version: "3.9"

services:
    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/.env:/frontend/.env
            - ./frontend/:/frontend/
            - /frontend/node_modules
            - /frontend/.next

    platform:
        container_name: platform
        build:
            context: ./platform
            target: prod
        ports:
            - "8000:8000"
        restart: always
        volumes:
            - ./platform:/app/src/
        env_file:
            - frontend/.env
        environment:
            PLATFORM_HOST: 0.0.0.0
            PLATFORM_DB_PORT: "3307"
            PLATFORM_DB_HOST: sass_scaffold_db
            PLATFORM_DB_BASE: "platform"
            PLATFORM_DB_USER: "platform"
            PLATFORM_DB_PASS: "platform"
        depends_on:
            - sass_scaffold_db

    sass_scaffold_db:
        image: mysql:8.0
        container_name: sass_scaffold_db
        restart: always
        build:
            context: ./db
        ports:
            - "3308:3307"
        environment:
            MYSQL_DATABASE: "sass_platform"
            MYSQL_USER: "sass_platform"
            MYSQL_PASSWORD: "sass_platform"
            MYSQL_ROOT_PASSWORD: "sass_platform"
            MYSQL_TCP_PORT: 3307
        volumes:
            - sass_scaffold_db:/var/lib/mysql
        command:
            [
                "mysqld",
                "--character-set-server=utf8mb4",
                "--collation-server=utf8mb4_unicode_ci",
            ]

volumes:
    sass_scaffold_db:
